/* Exemplo de Programa na linguagem L */

Var integer n[3], x, z;
Var integer n = 'x';
Var integer n;
/* Char nome[40]; */
MAXITER=0x04;

/* Programa Principal */

  write("Digite seu nome: ");
  readln(nome);
  For n=1 to MAXITER step do {
    writeln("Ola' ", oa, "abc");
    write("Ola' ", oa, "abc");
  };

  if 4 or 5 then {
    write("teste");
  } else {
    readln(nome);
  }