/* Exemplo de Programa na linguagem L */

Var integer n,y=3,o=65;
Var char nome='x',vitor=0x4A;
Var char nomw=0x44;
const l=45;
Var char k;
Var char qw,q,e;
Integer wi[2048];
Integer wj[2048];
Integer nomw3 = 3, nom2;
char yi[2];
Const MAXITER[3] = "asd";

k = n + nom2; /* arrumar */
o = (wi = wj);
yi = "bc";
write((3 + 2));
write(3);
writeln(k);
/* Programa Principal */

  write("Digite seu nome: ");
  readln(nome);
  n = n + 1;
  For nom2= n to 1 step l do {
      writeln("Ola' ",nome);
	}