/* Exemplo de Programa na linguagem L */

Var integer n,y=3,o=65;
Var char nome='x',vitor=0x4A;
Var char nomw=0x44;
/*const l=45;*/
Var char k;
Var char qw,q,e;
Integer wi[2048];
Integer nomw3 = 3, nom2;
char yi[4096];
Const MAXITER[3] = "asd";

k = -n * y + 3 % nomw3;
write(MAXITER);
/* Programa Principal */

  write("Digite seu nome: ");
  readln(nome);
  For nom2= n to 1 do {
      writeln("Ola' ",nome);
	}